apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumiday-deployment
  labels:
    app: lumiday-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lumiday-pod
  template:
    metadata:
      name: lumiday-deployment
      labels:
        app: lumiday-pod
    spec:
      containers:
        - name: lumiday-container
          image: rappire/lumiday:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 30
            periodSeconds: 10
      restartPolicy: Always
      