apiVersion: v1
kind: Service
metadata:
  name: lumiday-api-service
  namespace: lumiday
spec:
  type: NodePort
  selector:
    app: lumiday-pod
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30010