spring:
  application:
    name: core-api
  config:
    import:
      - db-jpa.yml
  web:
    resources:
      add-mappings: false

minio:
  url: http://localhost:9000
  access-key: G1ctsDXJ4VrolSvQuqjn
  secret-key: g0Ii5LQ8SNFMHevmYLYMrq7YvdAdSPdXr307af0D
  bucket: lumiday-image
