spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_batch_fetch_size: 100
---
spring.config.activate.on-profile: local-dev

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

storage:
  datasource:
    jpa:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${storage.database.core-db.url}
      username: ${storage.database.core-db.username}
      password: ${storage.database.core-db.password}