spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_batch_fetch_size: 100
---
spring.config.activate.on-profile: local-dev

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

storage:
  datasource:
    jpa:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://129.154.62.103:32304/lumyday
      username: rappire
      password: 1234
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        idle-timeout: 30000
        pool-name: HikariCP
