name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v3

      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lumiday:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64


      - name: VM에 배포
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            kubectl set image deployments lumiday-deployment lumiday-container=${{ secrets.DOCKERHUB_USERNAME }}/lumiday:${{ github.sha }} -n lumiday
            
            TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            PR_TITLE="${{ github.event.pull_request.title }}"
            
            kubectl annotate deployment/${DEPLOYMENT} \
            deploy.kubernetes.io/last-deploy="${TIMESTAMP}" \
            deploy.kubernetes.io/pr-title="${PR_TITLE}" \
            --overwrite -n ${NAMESPACE}
